### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by JimDeSmet** [Kikobeats/compress-brotli#9]
When using the library in my angular application I am getting following errors

ERROR in ./node_modules/compress-brotli/src/index.js 7:15-30

Module not found: Error: Can't resolve 'util' in 'C:\Users\myName\source\repos\MyApp\Frontend\*****\node_modules\compress-brotli\src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

ERROR in ./node_modules/compress-brotli/src/index.js 12:11-26

Module not found: Error: Can't resolve 'zlib' in 'C:\Users\myName\source\repos\myApp\Frontend\****\node_modules\compress-brotli\src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
	- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "zlib": false }
	
	
How do I resolve these errors ?

**Comment by Kikobeats** [comment]
Hello, did you read the error explanation? It's actually pretty great 😅

This is a Node.js library. If you want to bundle it for the browser, you have to polyfill Node.js APIs (util and zlib)
